<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
    <?php 
        $smartshippinghelper = $this->helper('Smarttshipping\Shipping\Helper\Data'); 
        $origincountyid = $smartshippinghelper->getDefautOriginCountryId();
    ?>
    <form id="edit_form" method="post" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>">
        <?= $block->getBlockHtml('formkey') ?>
        <?php  $_order = $block->getShipment()->getOrder() ?>
        <?php  
            $shippingAddress = $_order->getShippingAddress(); 
            $shippingaddressid = $shippingAddress->getCountryId();
        ?>
        <?= $block->getChildHtml('order_info') ?>
        <div class="admin__page-section">
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')) ?></span>
            </div>
            <div class="admin__page-section-content">
                <div class="admin__page-section-item order-payment-method">
                    <?php /* Billing Address */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?=$block->escapeHtml(__('Payment Information')) ?></span>
                    </div>
                    <div class="admin__page-section-item-content">
                        <div><?= $block->getPaymentHtml() ?></div>
                        <div class="order-payment-currency"><?= $block->escapeHtml(__('The order was placed using %1.', $_order->getOrderCurrencyCode())) ?></div>
                    </div>
                </div>
                <div class="admin__page-section-item order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= $block->escapeHtml(__('Shipping Information')) ?></span>
                    </div>
                    <div class="admin__page-section-item-content shipping-description-wrapper">
                        <div class="shipping-description-title">
                            <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                        </div>
                        <div class="shipping-description-content">
                            <?= $block->escapeHtml(__('Total Shipping Charges')) ?>:

                            <?php if ($this->helper(Magento\Tax\Helper\Data::class)->displayShippingPriceIncludingTax()): ?>
                                <?php $_excl = $block->displayShippingPriceInclTax($_order); ?>
                            <?php else: ?>
                                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                            <?php endif; ?>
                            <?php $_incl = $block->displayShippingPriceInclTax($_order); ?>
                            <?= /** @noEscape */ $_excl ?>
                            <?php if ($this->helper(Magento\Tax\Helper\Data::class)->displayShippingBothPrices()
                                && $_incl != $_excl): ?>
                                (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
                            <?php endif; ?>
                        </div>
                        <div style="margin-top: 10px; ">
                            <input class="admin__control-text _has-datepicker cus_date" type="datetime-local" id="pickdatetime" name="pickdatetime" data-validate='{"required":true}'/>
                        </div>
                        <?php if($origincountyid != $shippingaddressid): ?>
                        <div class="int-shipping-info">
                            <input type="hidden" name="is_international" value="yes" />
                            <input type="hidden" name="shipping_address_country_id" value="<?php echo $shippingaddressid; ?>" />
                            <div class="shipping-description-title">International Shipping</div>
                            <div class="shi-lab">
                                <label class="admin__field-label" for="cars">Import Export Type:</label>
                                <select class="admin__control-select" id="ImportExportType" name="importexporttype" data-validate='{"required":true}'/>
                                    <option value="Permanent" selected>Permanent</option>
                                    <option value="Temporary">Temporary</option>
                                    <option value="Repair">Repair</option>
                                    <option value="Return">Return</option>
                                </select>
                            </div>
                            <div class="shi-lab">
                                <label class="admin__field-label" for="cars">Customs Broker Name:</label>
                                <input type="text" class="admin__control-text" name="customsbrokername" id="customsbrokername" data-validate='{"required":true}'/>
                            </div>
                             <div class="shi-lab">
                                <label class="admin__field-label" for="cars">Importer Of Record Name:</label>
                                <input type="text" class="admin__control-text" name="importerofrecordname" id="importerofrecordname" data-validate='{"required":true}'/>
                            </div>
                        </div>
                    <?php endif; ?>
                    </div>
                    <div><?= $block->getChildHtml('shipment_tracking') ?></div>
                </div>
            </div>
        </div>
        <div><?= $block->getChildHtml('extra_shipment_info') ?></div>
        <div id="ship_items_container">
            <?= $block->getItemsHtml() ?>
        </div>
    </form>
    <script>
        require([
            "jquery",
            "mage/mage",
            "prototype"
        ], function(jQuery){
            jQuery('#edit_form').mage('form').mage('validation');

        });
    </script>
<?= $block->getChildHtml('shipment_packaging');
