<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#connect_span');
        var buttonText = '<?php echo $block->getButtonText()?>';
        var buttonErrorText = '<?php echo $block->getButtonErrorText()?>';
        var buttonSuccessText = '<?php echo $block->getButtonSuccessText()?>';

        jQuery('#connect_button').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    jQuery('#connect_button span').html('wait...')
                    jQuery('#collect_message_span').text('');
                    jQuery('#error-custom').remove();
                },
                onSuccess: function(response) {
                    var responce = response.responseJSON;
                    if(responce.error){
                        jQuery('#connect_button').css({"color": "white", "background": "red"});
                        jQuery('#connect_button').parent().append('<p id="error-custom" style="color:red;">'+responce.error+'</p>');
                        jQuery('#connect_button span').html(buttonErrorText);
                    } 
                    else {
                       jQuery('#connect_button span').html(buttonSuccessText)
                       jQuery('#connect_button').css({"color": "white", "background": "green"});
                       jQuery('#connect_button span').html(buttonSuccessText);
                    }
                    
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>